# Generated by Django 3.2 on 2021-05-01 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('category', models.CharField(choices=[('laptops', 'Компьютеры'), ('keyboards', 'Клавиатура'), ('others', 'Другое'), ('mouses', 'Мышки'), ('headphones', 'Наушники')], default='others', max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='user_pics', verbose_name='Картинка товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('description', models.TextField(max_length=2000, verbose_name='Текст отзыва')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('moderated', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='webapp.product')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
            },
        ),
    ]
