# Generated by Django 3.2 on 2021-05-01 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_alter_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ManyToManyField(default=1, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
